#!/mnt/hdd/hmiwa
cat yana_j_f3_analysis_altai.geno > yana_j_f3_analysis2_altai.geno;echo "yana_j altai"
cat yana_j_f3_analysis_chagyrskaya.geno > yana_j_f3_analysis2_chagyrskaya.geno;echo "yana_j chagyrskaya"
cat yana_j_f3_analysis_vindija.geno > yana_j_f3_analysis2_vindija.geno;echo "yana_j vindija"
cat yana_j_f3_analysis_denisova.geno > yana_j_f3_analysis2_denisova.geno;echo "yana_j denisova"
cat yana_j_f3_analysis_altai.snp > yana_j_f3_analysis2_altai.snp;echo "yana_j altai"
cat yana_j_f3_analysis_chagyrskaya.snp > yana_j_f3_analysis2_chagyrskaya.snp;echo "yana_j chagyrskaya"
cat yana_j_f3_analysis_vindija.snp > yana_j_f3_analysis2_vindija.snp;echo "yana_j vindija"
cat yana_j_f3_analysis_denisova.snp > yana_j_f3_analysis2_denisova.snp;echo "yana_j denisova"
cat yanarhs_f3_analysis_altai.geno > yanarhs_f3_analysis2_altai.geno;echo "yanarhs altai"
cat yanarhs_f3_analysis_chagyrskaya.geno > yanarhs_f3_analysis2_chagyrskaya.geno;echo "yanarhs chagyrskaya"
cat yanarhs_f3_analysis_vindija.geno > yanarhs_f3_analysis2_vindija.geno;echo "yanarhs vindija"
cat yanarhs_f3_analysis_denisova.geno > yanarhs_f3_analysis2_denisova.geno;echo "yanarhs denisova"
cat yanarhs_f3_analysis_altai.snp > yanarhs_f3_analysis2_altai.snp;echo "yanarhs altai"
cat yanarhs_f3_analysis_chagyrskaya.snp > yanarhs_f3_analysis2_chagyrskaya.snp;echo "yanarhs chagyrskaya"
cat yanarhs_f3_analysis_vindija.snp > yanarhs_f3_analysis2_vindija.snp;echo "yanarhs vindija"
cat yanarhs_f3_analysis_denisova.snp > yanarhs_f3_analysis2_denisova.snp;echo "yanarhs denisova"