#!/mnt/hdd/hmiwa
echo "start:`date`"
cat yanarhs_f3_analysis_altai.geno > yanarhs_f3_analysis5_altai.geno;echo "yanarhs5 altai"
cat yanarhs_f3_analysis_chagyrskaya.geno > yanarhs_f3_analysis5_chagyrskaya.geno;echo "yanarhs5 chagyrskaya"
cat yanarhs_f3_analysis_vindija.geno > yanarhs_f3_analysis5_vindija.geno;echo "yanarhs5 vindija"
cat yanarhs_f3_analysis_denisova.geno > yanarhs_f3_analysis5_denisova.geno;echo "yanarhs5 denisova"
cat yanarhs_f3_analysis_altai.snp > yanarhs_f3_analysis5_altai.snp;echo "yanarhs5 altai"
cat yanarhs_f3_analysis_chagyrskaya.snp > yanarhs_f3_analysis5_chagyrskaya.snp;echo "yanarhs5 chagyrskaya"
cat yanarhs_f3_analysis_vindija.snp > yanarhs_f3_analysis5_vindija.snp;echo "yanarhs5 vindija"
cat yanarhs_f3_analysis_denisova.snp > yanarhs_f3_analysis5_denisova.snp;echo "yanarhs5 denisova"
#cat yanarhs_f3_analysis_altai.geno > yanarhs_f3_analysis4_altai.geno;echo "yanarhs4 altai"
#cat yanarhs_f3_analysis_chagyrskaya.geno > yanarhs_f3_analysis4_chagyrskaya.geno;echo "yanarhs4 chagyrskaya"
#cat yanarhs_f3_analysis_vindija.geno > yanarhs_f3_analysis4_vindija.geno;echo "yanarhs4 vindija"
#cat yanarhs_f3_analysis_denisova.geno > yanarhs_f3_analysis4_denisova.geno;echo "yanarhs4 denisova"
#cat yanarhs_f3_analysis_altai.snp > yanarhs_f3_analysis4_altai.snp;echo "yanarhs4 altai"
#cat yanarhs_f3_analysis_chagyrskaya.snp > yanarhs_f3_analysis4_chagyrskaya.snp;echo "yanarhs4 chagyrskaya"
#cat yanarhs_f3_analysis_vindija.snp > yanarhs_f3_analysis4_vindija.snp;echo "yanarhs4 vindija"
#cat yanarhs_f3_analysis_denisova.snp > yanarhs_f3_analysis4_denisova.snp;echo "yanarhs4 denisova"
echo "finish:`date`"